### ISSUE TITLE
How to upload images?

### ISSUE THREAD

**Issue by ahmadawais** [mikejolley/github-to-wordpress-deploy-script#5]
How to upload images in assets folders using this script?

**Comment by mikejolley** [comment]
This script doesn't handle assets, only the release itself.

**Comment by ahmadawais** [comment]
@mikejolley Thanks for letting me know.

**Comment by flowdee** [comment]
Can you add support for assets @mikejolley ? Other scripts like [this](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy) handle it very well.

**Comment by mikejolley** [comment]
You can, but I have no plans. Don't need it personally :)

**Comment by ahmadawais** [comment]
@flowdee I have modified and built a script that handles assets. Will share it after removing and cleaning my personal workflow, a 4 months old version is here [WPGitDelpoy-Script](https://github.com/ahmadawais/WPGitDeploy-Script)

**Comment by mihdan** [comment]
@ahmadawais I have not found in your script processing directory assets
